### ISSUE TITLE
 A token must be specified for ajax encryption

### ISSUE THREAD

**Issue by 274188A** [lsgs/redcap-project-autocomplete#1]
Hi @lsgs,

I had to disable this EM due to some auth issues so i thought I'd just log it here.

>[23-Jun-2023 07:33:52 Australia/Perth] Chunked Log Part 1 of 3:
Exception: A token must be specified for ajax encryption. in D:\redcap_prod\redcap_v13.7.1\ExternalModules\classes\ExternalModules.php:8142
Stack trace:
#0 D:\redcap_prod\redcap_v13.7.1\ExternalModules\classes\framework\Framework.php(2131): ExternalModules\ExternalModules::initAjaxCrypto(false)
#1 D:\redcap_prod\redcap_v13.7.1\ExternalModules\classes\framework\Framework.php(2251): ExternalModules\Framework->getAjaxSettings()
#2 [internal function]: ExternalModules\Framework->initializeJavascriptModuleObject()
#3 D:\redcap_prod\redcap_v13.7.1\ExternalModules\classes\framework\Framework.php(314): call_user_func_array(Array, Array)
#4 D:\redcap_prod\redcap_v13.7.1\ExternalModules\classes\AbstractExternalModule.php(97): ExternalModules\Framework->callFromModuleInstance('initializeJavas...', Array)
#5 D:\redcap_prod\redcap_v13.7.1\ExternalModules\classes\AbstractExternalModule.php(158): ExternalModules\AbstractExternalModule->__call('initializeJavas...', Array)
#6 D:\redcap_prod\modules\pro
[23-Jun-2023 07:33:52 Australia/Perth] Chunked Log Part 2 of 3:
ject_autocomplete_v1.1.0\ProjectAutoComplete.php(82): ExternalModules\AbstractExternalModule->initializeJavascriptModuleObject()
#7 D:\redcap_prod\redcap_v13.7.1\ExternalModules\classes\ExternalModules.php(3162): MCRI\ProjectAutoComplete\ProjectAutoComplete->redcap_every_page_top(NULL)
#8 D:\redcap_prod\redcap_v13.7.1\ExternalModules\classes\ExternalModules.php(3327): ExternalModules\ExternalModules::startHook('project_autocom...', 'v1.1.0', Array)
#9 D:\redcap_prod\redcap_v13.7.1\ExternalModules\classes\ExternalModules.php(3360): ExternalModules\ExternalModules::ExternalModules\{closure}('**project_autocom**...', 'v1.1.0')
#10 D:\redcap_prod\redcap_v13.7.1\Classes\Hooks.php(42): ExternalModules\ExternalModules::callHook('every_page_top', Array)
#11 D:\redcap_prod\redcap_v13.7.1\Classes\HtmlPage.php(144): Hooks::call('redcap_every_pa...', Array)
#12 D:\redcap_prod\redcap_v13.7.1\Classes\Authentication.php(1324): HtmlPage->PrintHeader()
#13 D:\redcap_prod\redcap_v13.7.1\Classes\Authenticati
[23-Jun-2023 07:33:52 Australia/Perth] Chunked Log Part 3 of 3:
on.php(859): Authentication::renderTwoFactorLoginPage()
#14 D:\redcap_prod\redcap_v13.7.1\Classes\System.php(788): Authentication::authenticate()
#15 D:\redcap_prod\redcap_v13.7.1\Config\init_global.php(7): System::initGlobalPage()
#16 D:\redcap_prod\redcap_v13.7.1\home.php(5): require_once('D:\\redcap_prod\\...')
#17 D:\redcap_prod\index.php(9): include('D:\\redcap_prod\\...')
#18 {main}

**Comment by lsgs** [comment]
Thanks for the report @274188A. It looks from the message like the exception was thrown when logging in and requiring 2FA entry. Are you able to replicate that reliably? I can't seem to do so in our instances.

**Comment by 274188A** [comment]
@lsgs Are you on IIS? 

It might be something funky going on with as you mentioned cookies or something in our environment but your EM just happened to log it.  I don't believe now that this is a bug in the EM.

I have re-installed it to try and trigger the same error - in progress...

>REDCap 13.7.2 · PHP 8.2.7 (Windows OS) · MySQL 8.0.33

**Comment by 274188A** [comment]
Yes, came up again yesterday - I have no idea but it does not thankfully affect any other part of REDCap

>[11-Jul-2023 08:13:32 Australia/Perth] Chunked Log Part 1 of 3:
Exception: A token must be specified for ajax encryption. in D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php:8142
Stack trace:
#0 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\framework\Framework.php(2131): ExternalModules\ExternalModules::initAjaxCrypto(false)
#1 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\framework\Framework.php(2251): ExternalModules\Framework->getAjaxSettings()
#2 [internal function]: ExternalModules\Framework->initializeJavascriptModuleObject()
#3 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\framework\Framework.php(314): call_user_func_array(Array, Array)
#4 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\AbstractExternalModule.php(97): ExternalModules\Framework->callFromModuleInstance('...', Array)
#5 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\AbstractExternalModule.php(158): ExternalModules\AbstractExternalModule->__call('...', Array)
#6 D:\redcap_prod\modules\project_autocomplete_v1.1.0\Proje
[11-Jul-2023 08:13:32 Australia/Perth] Chunked Log Part 2 of 3:
ctAutoComplete.php(82): ExternalModules\AbstractExternalModule->initializeJavascriptModuleObject()
#7 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php(3162): MCRI\ProjectAutoComplete\ProjectAutoComplete->redcap_every_page_top(NULL)
#8 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php(3327): ExternalModules\ExternalModules::startHook('...', '...', Array)
#9 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php(3360): ExternalModules\ExternalModules::ExternalModules\{closure}('...', '...')
#10 D:\redcap_prod\redcap_v13.8.1\Classes\Hooks.php(42): ExternalModules\ExternalModules::callHook('...', Array)
#11 D:\redcap_prod\redcap_v13.8.1\Classes\HtmlPage.php(144): Hooks::call('...', Array)
#12 D:\redcap_prod\redcap_v13.8.1\Classes\Authentication.php(1324): HtmlPage->PrintHeader()
#13 D:\redcap_prod\redcap_v13.8.1\Classes\Authentication.php(859): Authentication::renderTwoFactorLoginPage()
#14 D:\redcap_prod\redcap_v13.8.1\Cl
[11-Jul-2023 08:13:32 Australia/Perth] Chunked Log Part 3 of 3:
asses\System.php(747): Authentication::authenticate()
#15 D:\redcap_prod\redcap_v13.8.1\Config\init_global.php(7): System::initGlobalPage()
#16 D:\redcap_prod\redcap_v13.8.1\home.php(5): require_once('...')
#17 D:\redcap_prod\index.php(9): include('...')
#18 {main}
[11-Jul-2023 10:53:44 Australia/Perth] Chunked Log Part 1 of 3:
Exception: A token must be specified for ajax encryption. in D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php:8142
Stack trace:
#0 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\framework\Framework.php(2131): ExternalModules\ExternalModules::initAjaxCrypto(false)
#1 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\framework\Framework.php(2251): ExternalModules\Framework->getAjaxSettings()
#2 [internal function]: ExternalModules\Framework->initializeJavascriptModuleObject()
#3 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\framework\Framework.php(314): call_user_func_array(Array, Array)
#4 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\AbstractExternalModule.php(97): ExternalModules\Framework->callFromModuleInstance('...', Array)
#5 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\AbstractExternalModule.php(158): ExternalModules\AbstractExternalModule->__call('...', Array)
#6 D:\redcap_prod\modules\project_autocomplete_v1.1.0\Proje
[11-Jul-2023 10:53:44 Australia/Perth] Chunked Log Part 2 of 3:
ctAutoComplete.php(82): ExternalModules\AbstractExternalModule->initializeJavascriptModuleObject()
#7 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php(3162): MCRI\ProjectAutoComplete\ProjectAutoComplete->redcap_every_page_top(NULL)
#8 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php(3327): ExternalModules\ExternalModules::startHook('...', '...', Array)
#9 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php(3360): ExternalModules\ExternalModules::ExternalModules\{closure}('...', '...')
#10 D:\redcap_prod\redcap_v13.8.1\Classes\Hooks.php(42): ExternalModules\ExternalModules::callHook('...', Array)
#11 D:\redcap_prod\redcap_v13.8.1\Classes\HtmlPage.php(144): Hooks::call('...', Array)
#12 D:\redcap_prod\redcap_v13.8.1\Classes\Authentication.php(1324): HtmlPage->PrintHeader()
#13 D:\redcap_prod\redcap_v13.8.1\Classes\Authentication.php(859): Authentication::renderTwoFactorLoginPage()
#14 D:\redcap_prod\redcap_v13.8.1\Cl
[11-Jul-2023 10:53:44 Australia/Perth] Chunked Log Part 3 of 3:
asses\System.php(747): Authentication::authenticate()
#15 D:\redcap_prod\redcap_v13.8.1\Config\init_global.php(7): System::initGlobalPage()
#16 D:\redcap_prod\redcap_v13.8.1\home.php(5): require_once('...')
#17 D:\redcap_prod\index.php(9): include('...')
#18 {main}
[12-Jul-2023 11:19:18 Australia/Perth] Chunked Log Part 1 of 3:
Exception: A token must be specified for ajax encryption. in D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php:8142
Stack trace:
#0 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\framework\Framework.php(2131): ExternalModules\ExternalModules::initAjaxCrypto(false)
#1 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\framework\Framework.php(2251): ExternalModules\Framework->getAjaxSettings()
#2 [internal function]: ExternalModules\Framework->initializeJavascriptModuleObject()
#3 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\framework\Framework.php(314): call_user_func_array(Array, Array)
#4 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\AbstractExternalModule.php(97): ExternalModules\Framework->callFromModuleInstance('...', Array)
#5 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\AbstractExternalModule.php(158): ExternalModules\AbstractExternalModule->__call('...', Array)
#6 D:\redcap_prod\modules\project_autocomplete_v1.1.0\Proje
[12-Jul-2023 11:19:18 Australia/Perth] Chunked Log Part 2 of 3:
ctAutoComplete.php(82): ExternalModules\AbstractExternalModule->initializeJavascriptModuleObject()
#7 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php(3162): MCRI\ProjectAutoComplete\ProjectAutoComplete->redcap_every_page_top(NULL)
#8 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php(3327): ExternalModules\ExternalModules::startHook('...', '...', Array)
#9 D:\redcap_prod\redcap_v13.8.1\ExternalModules\classes\ExternalModules.php(3360): ExternalModules\ExternalModules::ExternalModules\{closure}('...', '...')
#10 D:\redcap_prod\redcap_v13.8.1\Classes\Hooks.php(42): ExternalModules\ExternalModules::callHook('...', Array)
#11 D:\redcap_prod\redcap_v13.8.1\Classes\HtmlPage.php(144): Hooks::call('...', Array)
#12 D:\redcap_prod\redcap_v13.8.1\Classes\Authentication.php(1324): HtmlPage->PrintHeader()
#13 D:\redcap_prod\redcap_v13.8.1\Classes\Authentication.php(859): Authentication::renderTwoFactorLoginPage()
#14 D:\redcap_prod\redcap_v13.8.1\Cl
[12-Jul-2023 11:19:18 Australia/Perth] Chunked Log Part 3 of 3:
asses\System.php(747): Authentication::authenticate()
#15 D:\redcap_prod\redcap_v13.8.1\Config\init_global.php(7): System::initGlobalPage()
#16 D:\redcap_prod\redcap_v13.8.1\home.php(5): require_once('...')
#17 D:\redcap_prod\index.php(9): include('...')
#18 {main}
